image: hexpm/elixir:1.12.1-erlang-24.0.3-alpine-3.13.3

variables:
  MIX_TARGET: rpi4

before_script:
  - mkdir ~/.ssh
  - echo "$NERVES_SSH_KEY" > ~/.ssh/id_rsa.pub
  - mix local.rebar --force
  - mix local.hex --force
  - mix archive.install --force hex nerves_bootstrap
  - mix deps.get

mix:
  script:
    - mix firmware
  artifacts:
    paths:
      - _build/

