image: hexpm/elixir:1.12.1-erlang-24.0.3-alpine-3.13.3

variables:
  MIX_TARGET: containers_rpi4

before_script:
  - apk add --update --no-cache openssh git
    make gcc g++ bash which sed binutils gzip bzip2 perl tar cpio rsync file
    squashfs-tools fwup
    curl ncurses-libs cmake openssl-dev
    bc m4 xz unzip patch python2
  - mkdir ~/.ssh
  - eval "$(ssh-agent)"
  - echo "$NERVES_SSH_KEY" > ~/.ssh/id_rsa.pub
  - echo "$NERVES_GITHUB_KEY" > ~/.ssh/github.key
  - chmod 600 ~/.ssh/github.key
  - ssh-add ~/.ssh/github.key
  - ssh-add -l
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - mix local.rebar --force
  - mix local.hex --force
  - mix archive.install --force hex nerves_bootstrap
  - mix deps.get

mix:
  script:
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - _build/

