variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"
  NERVES_BUILD_VERSION: 1.17.0

stages:
  - prepare
  - build

#####################

build_x86_64:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$NERVES_BUILD_VERSION
  stage: build
  variables:
    MIX_TARGET: x86_64
  before_script:
    - cd nerves_containers/
    - bash ../_init_ci.sh
  script:
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - nerves_containers/_build/x86_64_dev/nerves/images/*.fw
  only:
    refs:
      - main
      - development

build_x86_64_uefi:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$NERVES_BUILD_VERSION
  stage: build
  variables:
    MIX_TARGET: x86_64_efi
  before_script:
    - cd nerves_containers/
    - bash ../_init_ci.sh
  script:
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - nerves_containers/_build/x86_64_efi_dev/nerves/images/*.fw
  only:
    refs:
      - main
      - development

build_rpi:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$NERVES_BUILD_VERSION
  stage: build
  variables:
    MIX_TARGET: rpi
  before_script:
    - cd nerves_containers/
    - bash ../_init_ci.sh
  script:
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - nerves_containers/_build/rpi_dev/nerves/images/*.fw
  only:
    refs:
      - main
      - development

build_rpi3:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$NERVES_BUILD_VERSION
  stage: build
  variables:
    MIX_TARGET: rpi3
  before_script:
    - cd nerves_containers/
    - bash ../_init_ci.sh
  script:
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - nerves_containers/_build/rpi3_dev/nerves/images/*.fw
  only:
    refs:
      - main
      - development

build_rpi3_64:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$NERVES_BUILD_VERSION
  stage: build
  variables:
    MIX_TARGET: rpi3_64
  before_script:
    - cd nerves_containers/
    - bash ../_init_ci.sh
  script:
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - nerves_containers/_build/rpi3_64_dev/nerves/images/*.fw
  only:
    refs:
      - main
      - development

build_rpi4:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$NERVES_BUILD_VERSION
  stage: build
  variables:
    MIX_TARGET: rpi4
  before_script:
    - cd nerves_containers/
    - bash ../_init_ci.sh
  script:
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - nerves_containers/_build/rpi4_dev/nerves/images/*.fw
  only:
    refs:
      - main
      - development

build_bananapi_m1:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$NERVES_BUILD_VERSION
  stage: build
  variables:
    MIX_TARGET: bananapi_m1
  before_script:
    - cd nerves_containers/
    - bash ../_init_ci.sh
  script:
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - nerves_containers/_build/bananapi_m1_dev/nerves/images/*.fw
  only:
    refs:
      - main
      - development
