variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"

stages:
  - prepare
  - build

#####################

build_rpi4:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$CI_COMMIT_REF_NAME
  stage: build
  variables:
    MIX_TARGET: rpi4
  script:
    - bash _init_ci.sh
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - _build/rpi4_*/nerves/images/*.fw
  cache:
    key: build-cache-$CI_COMMIT_REF_SLUG
    paths:
      - _build/
  only:
    refs:
      - main
      - development

build_x86_64:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$CI_COMMIT_REF_NAME
  stage: build
  variables:
    MIX_TARGET: x86_64
  script:
    - bash _init_ci.sh
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - _build/x86_64_*/nerves/images/*.fw
  cache:
    key: build-cache-$CI_COMMIT_REF_SLUG
    paths:
      - _build/
  only:
    refs:
      - main
      - development

build_x86_64_uefi:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$CI_COMMIT_REF_NAME
  stage: build
  variables:
    MIX_TARGET: x86_64_efi
  script:
    - bash _init_ci.sh
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - _build/x86_64_efi_*/nerves/images/*.fw
  cache:
    key: build-cache-$CI_COMMIT_REF_SLUG
    paths:
      - _build/
  only:
    refs:
      - main
      - development

build_rpi:
  image: $CI_REGISTRY/nerves-containers/nerves_ci/buildimage:$CI_COMMIT_REF_NAME
  stage: build
  variables:
    MIX_TARGET: rpi
  script:
    - bash _init_ci.sh
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - _build/rpi_*/nerves/images/*.fw
  cache:
    key: build-cache-$CI_COMMIT_REF_SLUG
    paths:
      - _build/
  only:
    refs:
      - main
      - development
