variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"

stages:
  - prepare
  - build

##########################################
# The meta jobs are used to build the images that are actually used in the later stages
##########################################

meta-build-image:
  image: docker:stable
  services:
    - docker:dind
  stage: prepare
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd .meta
    - docker build --build-arg CI_REGISTRY=$CI_REGISTRY --build-arg IMAGE_TAG=$CI_COMMIT_REF_NAME -t $CI_REGISTRY_IMAGE/buildimage:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE/buildimage:$CI_COMMIT_REF_NAME
  only:
    refs:
      - main
      - stage
    changes:
      - .meta/Dockerfile

#####################

build_rpi4:
  image: $CI_REGISTRY_IMAGE/buildimage:$CI_COMMIT_REF_NAME
  stage: build
  variables:
    MIX_TARGET: rpi4
  script:
    - bash _init_ci.sh
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - _build/
  cache:
    key: build-cache-$CI_COMMIT_REF_SLUG
    paths:
      - _build/
  only:
    refs:
      - main

build_x86_64:
  image: $CI_REGISTRY_IMAGE/buildimage:$CI_COMMIT_REF_NAME
  stage: build
  variables:
    MIX_TARGET: x86_64
  script:
    - bash _init_ci.sh
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - _build/
  cache:
    key: build-cache-$CI_COMMIT_REF_SLUG
    paths:
      - _build/
  only:
    refs:
      - main

build_rpi:
  image: $CI_REGISTRY_IMAGE/buildimage:$CI_COMMIT_REF_NAME
  stage: build
  variables:
    MIX_TARGET: rpi
  script:
    - bash _init_ci.sh
    - mix firmware --verbosity=quiet
  artifacts:
    paths:
      - _build/
  cache:
    key: build-cache-$CI_COMMIT_REF_SLUG
    paths:
      - _build/
  only:
    refs:
      - main
